version: '3.9'
services:
  postgres:
    image: postgres:15
    container_name: postgres-dev
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: revistas
      POSTGRES_PASSWORD: revistas123
      POSTGRES_DB: revistas_ebd
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
